In [1]:
# Load packages
import pandas as pd
import numpy as np
import fastparquet

In [2]:
# Don't run this!!!
pop_data = pd.read_csv("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/Mid-sem Project/pop_data.csv", encoding='latin-1')
 # drop columns that aren't relevant
pop_data = pop_data.drop(columns = ["SUMLEV", "REGION", "DIVISION", "ESTIMATESBASE2000", "POPESTIMATE2000", 
"POPESTIMATE2001", "POPESTIMATE2002", "POPESTIMATE2010"])
pop_data.head()

,STATE,COUNTY,STNAME,CTYNAME,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP
0,1,0,Alabama,Alabama,4503491,4530729,4569805,4628981,4672840,4718206,4757938,4779736
1,1,1,Alabama,Autauga County,46800,48366,49676,51328,52405,53277,54135,54571
2,1,3,Alabama,Baldwin County,151509,156266,162183,168121,172404,175827,179406,182265
3,1,5,Alabama,Barbour County,28594,28287,28027,27861,27757,27808,27657,27457
4,1,7,Alabama,Bibb County,21399,21721,22042,22099,22438,22705,22941,22915

In [3]:
# Don't run this!!!
# Reading in pop data after 2010
pop_data_2 = pd.read_csv("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/Mid-sem Project/pop_data_2.csv", encoding='latin-1')
pop_data_2 = pop_data_2[["STNAME", "CTYNAME", "POPESTIMATE2011", "POPESTIMATE2012", "POPESTIMATE2013", "POPESTIMATE2014", "POPESTIMATE2015"]]

pop_data_2.head()

,STNAME,CTYNAME,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
0,Alabama,Alabama,4799069,4815588,4830081,4841799,4852347
1,Alabama,Autauga County,55227,54954,54727,54893,54864
2,Alabama,Baldwin County,186558,190145,194885,199183,202939
3,Alabama,Barbour County,27341,27169,26937,26755,26283
4,Alabama,Bibb County,22745,22667,22521,22553,22566

In [4]:
# Don't run this!!!
# Merging both datasets to have complete pop data

pop_merged = pd.merge(left = pop_data, right = pop_data_2)

In [5]:
# Don't run this!!!
# save file as parquet
pop_merged.to_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", 
engine = 'fastparquet')

In [6]:
# RUN FROM HERE
# Read in parquet data
#population = pd.read_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", engine = 'fastparquet')

population = pd.read_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", engine = 'fastparquet')

In [7]:
population.sample(15)

,STATE,COUNTY,STNAME,CTYNAME,POPESTIMATE2003,POPESTIMATE2004,POPESTIMATE2005,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
index,,,,,,,,,,,,,,,,,
1894,36,69,New York,Ontario County,102625,103385,104259,104644,105216,106302,107214,107931,108599,108611,109044,109334,109271
131,5,37,Arkansas,Cross County,18896,18782,18883,18525,18172,18200,17971,17870,17809,17703,17521,17181,17255
2498,47,59,Tennessee,Greene County,64614,65364,66369,67153,67840,68328,68744,68831,69173,68760,68336,68464,68586
1119,21,217,Kentucky,Taylor County,23388,23536,23755,23971,24078,24256,24367,24512,24991,25069,25159,25360,25586
1564,29,113,Missouri,Lincoln County,43580,44995,46945,49117,50758,51847,52243,52566,53051,53265,53785,54170,54567
2931,51,139,Virginia,Page County,23531,23527,23708,24045,24222,24208,24076,24042,23957,23841,23723,23784,23662
2105,39,55,Ohio,Geauga County,93042,93218,93614,93839,93742,93583,93446,93389,93292,93771,93846,93979,93894
930,20,51,Kansas,Ellis County,27507,27457,27429,27653,27710,28010,28353,28452,28765,29089,29030,28963,28999
2675,48,221,Texas,Hood County,44448,45411,46470,47952,48870,50112,50841,51182,51563,52129,52860,53812,55227
567,16,7,Idaho,Bear Lake County,6219,6170,6077,6071,6049,6027,6014,5986,5956,5892,5948,5926,5879
537,13,283,Georgia,Treutlen County,6924,6949,6679,6771,6773,6847,6906,6885,6824,6789,6687,6811,6803
3069,54,61,West Virginia,Monongalia County,85983,87101,88424,89656,90764,92200,94165,96189,99018,100915,102266,103480,104681
408,13,21,Georgia,Bibb County,153697,154159,154003,154510,154286,154384,155154,155547,156211,156606,155031,154329,153945
2905,51,83,Virginia,Halifax County,36645,36382,36340,36383,36338,36347,36293,36241,36000,35738,35386,35204,35103
2351,44,3,Rhode Island,Kent County,170641,170539,169815,168522,167515,167269,166766,166158,165278,164627,164358,164490,163747

In [8]:
#Rename columns

population.rename(columns = {'CENSUS2010POP': 'POPESTIMATE2010'}, inplace=True)

In [9]:
for col in population.columns:
    if col[:3] == "POP":
        population.rename(columns={col: col[-4:]}, inplace= True)

population.columns

Index(['STATE', 'COUNTY', 'STNAME', 'CTYNAME', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='object')

In [14]:
# melt the population fields
melted_pop = pd.melt(population, ["STATE", "COUNTY", "STNAME", "CTYNAME"])



# rename FIPS and Year Columns 

melted_pop.rename(columns = {"variable" : "Year", "value": "FIPS"}, inplace = True)

melted_pop.sample(14)

       STATE  COUNTY        STNAME            CTYNAME  Year    FIPS
38122     53      45    Washington       Mason County  2014   60604
9724       5      77      Arkansas         Lee County  2006   11067
41281     51     760      Virginia      Richmond city  2015  220856
15728     51     550      Virginia    Chesapeake city  2007  217450
22540      6      29    California        Kern County  2010  839631
41063     48     413         Texas  Schleicher County  2015    3195
11771     40      63      Oklahoma      Hughes County  2006   13450
5597      46       9  South Dakota   Bon Homme County  2004    7014
27818     42      17  Pennsylvania       Bucks County  2011  625938
3549      12      59       Florida      Holmes County  2004   19319
17665     31      59      Nebraska    Fillmore County  2008    5940
19850     17     191      Illinois       Wayne County  2009   16788
6999      17      17      Illinois        Cass County  2005   13670
7854      28      95   Mississippi      Monroe County  2005   37464

In [12]:
## Save to parquet the cleaned file

melted_pop.to_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", 
engine = 'fastparquet')