In [1]:
# Load packages
import pandas as pd
import numpy as np
import fastparquet

In [3]:
# Don't run this!!!
pop_data = pd.read_csv("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/Mid-sem Project/pop_data.csv", encoding='latin-1')
 # drop columns that aren't relevant
pop_data = pop_data.drop(columns = ["SUMLEV", "REGION", "DIVISION", "ESTIMATESBASE2000", "POPESTIMATE2000", 
"POPESTIMATE2001", "POPESTIMATE2002", "POPESTIMATE2003", "POPESTIMATE2004", "POPESTIMATE2005", "POPESTIMATE2010"])
pop_data.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/Mid-sem Project/pop_data.csv'

In [ ]:
# Don't run this!!!
# Reading in pop data after 2010
pop_data_2 = pd.read_csv("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/Mid-sem Project/pop_data_2.csv", encoding='latin-1')
pop_data_2 = pop_data_2[["STNAME", "CTYNAME", "POPESTIMATE2011", "POPESTIMATE2012", "POPESTIMATE2013", "POPESTIMATE2014", "POPESTIMATE2015"]]

pop_data_2.head()

,STNAME,CTYNAME,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
0,Alabama,Alabama,4799069,4815588,4830081,4841799,4852347
1,Alabama,Autauga County,55227,54954,54727,54893,54864
2,Alabama,Baldwin County,186558,190145,194885,199183,202939
3,Alabama,Barbour County,27341,27169,26937,26755,26283
4,Alabama,Bibb County,22745,22667,22521,22553,22566

In [ ]:
# Don't run this!!!
# Merging both datasets to have complete pop data

pop_merged = pd.merge(left = pop_data, right = pop_data_2)

In [ ]:
# Don't run this!!!
# save file as parquet
pop_merged.to_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", 
engine = 'fastparquet')

In [3]:
# RUN FROM HERE
# Read in parquet data
population = pd.read_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", engine = 'fastparquet')
#population = pd.read_parquet("/Users/erikafox/Desktop/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", engine = 'fastparquet')

In [4]:
population.sample(15)

,STATE,COUNTY,STNAME,CTYNAME,POPESTIMATE2006,POPESTIMATE2007,POPESTIMATE2008,POPESTIMATE2009,CENSUS2010POP,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
index,,,,,,,,,,,,,,
3081,54,85,West Virginia,Ritchie County,10588,10558,10516,10478,10449,10313,10250,10147,10077,10084
1325,26,145,Michigan,Saginaw County,205822,203144,201966,200835,200169,198899,198363,196794,195248,193305
2523,47,109,Tennessee,McNairy County,25445,25541,25766,25940,26075,26077,26142,26035,26032,25864
2521,47,105,Tennessee,Loudon County,45207,46294,47342,47940,48556,49188,49823,50386,50586,50916
2804,48,479,Texas,Webb County,229307,234594,240287,245908,250304,255935,260595,264430,267465,269865
3033,53,69,Washington,Wahkiakum County,3936,3975,4033,3995,3978,3992,4000,4034,4043,4023
1165,22,69,Louisiana,Natchitoches Parish,38984,39114,39244,39425,39566,39386,39339,39118,39124,39004
1576,29,137,Missouri,Monroe County,9219,9216,9157,9014,8840,8683,8692,8770,8737,8637
1440,28,31,Mississippi,Covington County,19555,19510,19594,19516,19568,19485,19443,19208,19151,19243
1818,34,29,New Jersey,Ocean County,561302,565356,569485,573123,576567,578876,579932,582059,584447,587091
1176,22,91,Louisiana,St. Helena Parish,11089,11070,11106,11154,11203,10955,10979,10771,10519,10457
545,13,299,Georgia,Ware County,35624,36016,36065,35985,36312,36274,35893,35743,35513,35327
2633,48,137,Texas,Edwards County,1995,2062,2084,2012,2002,1979,1990,1899,1904,1910
2599,48,69,Texas,Castro County,7780,7737,7758,7856,8062,8094,8262,8120,7927,7787
2058,38,69,North Dakota,Pierce County,4394,4368,4372,4329,4357,4367,4446,4419,4364,4273

In [5]:
#Rename columns
for col in population.columns:
    if "POPESTIMATE" in col:
        x= col[-4:]
        print(x)
        population.rename(columns={col:x},inplace=True)
population.rename(columns={"CENSUS2010POP":"2010"},inplace=True)
population

2006
2007
2008
2009
2011
2012
2013
2014
2015

,STATE,COUNTY,STNAME,CTYNAME,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
index,,,,,,,,,,,,,,
0,1,0,Alabama,Alabama,4628981,4672840,4718206,4757938,4779736,4799069,4815588,4830081,4841799,4852347
1,1,1,Alabama,Autauga County,51328,52405,53277,54135,54571,55227,54954,54727,54893,54864
2,1,3,Alabama,Baldwin County,168121,172404,175827,179406,182265,186558,190145,194885,199183,202939
3,1,5,Alabama,Barbour County,27861,27757,27808,27657,27457,27341,27169,26937,26755,26283
4,1,7,Alabama,Bibb County,22099,22438,22705,22941,22915,22745,22667,22521,22553,22566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3186,56,37,Wyoming,Sweetwater County,39749,41470,42358,44133,43806,43986,45002,45157,44948,44719
3187,56,39,Wyoming,Teton County,20014,20472,20988,21232,21294,21414,21624,22315,22773,23047
3188,56,41,Wyoming,Uinta County,19709,20171,20613,21054,21118,20896,20996,20951,20822,20763
3189,56,43,Wyoming,Washakie County,7979,8169,8229,8423,8533,8449,8409,8413,8273,8278
3190,56,45,Wyoming,Weston County,6717,7033,7133,7266,7208,7142,7077,7136,7138,7208

In [6]:
# melt the population fields
melted_pop = pd.melt(population, ["STATE", "COUNTY", "STNAME", "CTYNAME"])

melted_pop.sample(14)

       STATE  COUNTY          STNAME             CTYNAME variable   value
27901     45      35  South Carolina   Dorchester County     2014  148748
9104      48     315           Texas       Marion County     2008   10748
10331     18      93         Indiana     Lawrence County     2009   46138
20107     20     113          Kansas    McPherson County     2012   29221
14279     29      15        Missouri       Benton County     2010   19056
22922     16      43           Idaho      Fremont County     2013   12872
13555     18     159         Indiana       Tipton County     2010   15936
10950     27      81       Minnesota      Lincoln County     2009    5892
7624      25       9   Massachusetts        Essex County     2008  734361
30825     39      57            Ohio       Greene County     2015  164272
5520      42      95    Pennsylvania  Northampton County     2007  293212
25934     13      17         Georgia     Ben Hill County     2014   17449
22346      1      17         Alabama     Chambers County     2013   34139
22823     13     179         Georgia      Liberty County     2013   62341

In [7]:
# save final file as parquet
melted_pop.to_parquet("/Users/preetkhowaja/Documents/MIDS Fall 2021/Practicing DS/pds2021-opioids-pds6/10_modified_data/pop_final.parquet", 
engine = 'fastparquet')